export const chats = [
  {
    id: "1",
    name: "Jane Cooper",
    message: "Hey Bro! Let's do it...",
    time: "07:59 pm",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 2,
    online: true,
  },
  {
    id: "2",
    name: "Theresa Webb",
    message: "Hey Bro! Let's do it...",
    time: "02:30 pm",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 2,
    online: false,
  },
  {
    id: "3",
    name: "Leslie Alexander",
    message: "Hey Bro! Let's do it...",
    time: "07:13 pm",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 2,
    online: false,
  },
  {
    id: "4",
    name: "Arlene McCoy",
    message: "Sent",
    time: "08:42 am",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 0,
    online: false,
  },
  {
    id: "5",
    name: "Jacob Jones",
    message: "Sent",
    time: "01:08 pm",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 0,
    online: false,
  },
  {
    id: "6",
    name: "Devon Lane",
    message: "Sent",
    time: "05:14 pm",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 0,
    online: false,
  },
  {
    id: "7",
    name: "Guy Hawkins",
    message: "Sent",
    time: "03:48 am",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 0,
    online: false,
  },
  {
    id: "8",
    name: "Albert Flores",
    message: "Sent",
    time: "01:09 am",
    avatar: "https://i.ibb.co.com/3YvJKdsk/polok.jpg",
    unread: 0,
    online: false,
  },
];
